### ISSUE TITLE
[BENCHMARK LMM-CMAES]

### ISSUE THREAD

**Issue by joshnah** [CyberAgentAILab/cmaes#120]
Hello, currently I'm trying to implement the **local meta-model** CMAES algorithm from this [paper](https://hal.inria.fr/hal-00825840/document) with the help of your repository. I already plotted to see how the algorithm works.
Here is the link to my implementation in my fork: [https://github.com/joshnah/cmaes/blob/main/test-LMM-CMAES.py](https://github.com/joshnah/cmaes/blob/main/test-LMM-CMAES.py)

I would like to make use of your folder benchmark (with kurobako) do some performance tests with the original algorithm CMAES but I didn't succeed. Could you please give me some advices or instructions on this benchmark? Thank you in advance.

**Comment by c-bata** [comment]
Hi @joshnah!
Thank you for using `cmaes`! The following yaml file, which is a definition of GitHub Actions, may help you since it contains the full instructions to run kurobako benchmark.
https://github.com/CyberAgentAILab/cmaes/blob/v0.8.2/.github/workflows/benchmarks.yml#L11-L101

Furthermore, if you share the steps to reproduce the problem and error messages, we may be able to give you more detailed advice.

**Comment by joshnah** [comment]
Thank you for your reply :100:  I'll check it out
